#!/bin/bash

set -e
set -o pipefail

LATEST=node9.dockerfile

for DOCKERFILE in dockerfiles/**/*.dockerfile; do
	CONFIG=$(cat $DOCKERFILE)
	TAG=""
	TAG_MAJOR=""
	TAG_MAJOR_MINOR=""

	if [[ $CONFIG =~ node:((([0-9]+).([0-9]+)).([0-9]+)) ]]; then
		TAG=${BASH_REMATCH[1]}
		TAG_MAJOR=${BASH_REMATCH[3]}
		TAG_MAJOR_MINOR=${BASH_REMATCH[2]}
	else
		echo "Could not find version"
		exit 1
	fi

	if [[ $DOCKERFILE == *"light"* ]]; then
		TAG="$TAG-light"
		TAG_MAJOR="$TAG_MAJOR-light"
		TAG_MAJOR_MINOR="$TAG_MAJOR_MINOR-light"
	fi

	echo "Building $DOCKERFILE"
	docker build --no-cache -t juliusworks/node:$TAG -f $DOCKERFILE .

	echo "Tagging $TAG as $TAG_MAJOR_MINOR"
	docker tag juliusworks/node:$TAG juliusworks/node:$TAG_MAJOR_MINOR

	echo "Tagging $TAG as $TAG_MAJOR"
	docker tag juliusworks/node:$TAG juliusworks/node:$TAG_MAJOR

	if [ "$(basename $DOCKERFILE)" == "$LATEST" ]; then
		echo "Tagging $TAG as latest"
		if [[ $DOCKERFILE == *"light"* ]]; then
			docker tag juliusworks/node:$TAG juliusworks/node:latest-light
			docker tag juliusworks/node:$TAG juliusworks/node:light
		else
			docker tag juliusworks/node:$TAG juliusworks/node:latest
		fi
	fi

	echo "Pushing $DOCKERFILE"
	docker push juliusworks/node:$TAG
	docker push juliusworks/node:$TAG_MAJOR_MINOR
	docker push juliusworks/node:$TAG_MAJOR

	if [ "$(basename $DOCKERFILE)" == "$LATEST" ]; then
		if [[ $DOCKERFILE == *"light"* ]]; then
			docker push juliusworks/node:latest-light
			docker push juliusworks/node:light
		else
			docker push juliusworks/node:latest
		fi
	fi
done
